export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const BUDGET_NOTE_REPOSITORY = 'BUDGET_NOTE_REPOSITORY';
export const BUDGET_NOTE_DETAIL_REPOSITORY = 'BUDGET_NOTE_DETAIL_REPOSITORY';
export const MONTH_REPOSITORY = 'MONTH_REPOSITORY';
export const REQUEST_STATUS_REPOSITORY = 'REQUEST_STATUS_REPOSITORY';
export const STATE_REPOSITORY = 'STATE_REPOSITORY';
