export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const ACTIONS = 'ACTIONS';
export const APPROVER_REVIEWER = 'APPROVER_REVIEWER';
export const AVAILABILITY_CERTIFICATE_REPOSITORY =
    'AVAILABILITY_CERTIFICATE_REPOSITORY';
export const AVAILABILITY_CERTIFICATE_DETAIL_REPOSITORY =
    'AVAILABILITY_CERTIFICATE_DETAIL_REPOSITORY';
export const BUDGET_REPOSITORY = 'BUDGET_REPOSITORY';
export const BUDGET_NOTE_REPOSITORY = 'BUDGET_NOTE_REPOSITORY';
export const BUDGET_NOTE_DETAIL_REPOSITORY = 'BUDGET_NOTE_DETAIL_REPOSITORY';
export const CONCEPT_REPOSITORY = 'CONCEPT_REPOSITORY';
export const MODIFICATION_REQUEST_REPOSITORY =
    'MODIFICATION_REQUEST_REPOSITORY';
export const MONTH_REPOSITORY = 'MONTH_REPOSITORY';
export const REQUEST_STATUS_REPOSITORY = 'REQUEST_STATUS_REPOSITORY';
export const STATE_REPOSITORY = 'STATE_REPOSITORY';
export const SUBCONCEPT_REPOSITORY = 'SUBCONCEPT_REPOSITORY';
